name: Node.js CI/CD Pipeline

# Trigger the workflow on push to the main branch
on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]

# Define the jobs to run
jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Run this job only if build-and-test succeeds

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Print a deployment message (replace this with actual deployment commands)
      - name: Deploy application
        run: |
          echo "Deploying to production server..."
          ls ${{ github.workspace }}
          pwd
          df -h
          uptime
          date
          ls /
          cat /etc/*release
          hostname
          ip a
        
